// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibKzR061047KehYKc6dKsKjJ0RPKlAd4',
    appId: '1:1026142335848:web:23f222bbf502d01abb5cdd',
    messagingSenderId: '1026142335848',
    projectId: 'bookrading',
    authDomain: 'bookrading.firebaseapp.com',
    storageBucket: 'bookrading.appspot.com',
    measurementId: 'G-03ZN4DGPEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlRXEYj2w1HWiE9Y05wWeo271cf8DzLQ',
    appId: '1:1026142335848:android:ee95d96fe09553cabb5cdd',
    messagingSenderId: '1026142335848',
    projectId: 'bookrading',
    storageBucket: 'bookrading.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA7zuP9sptXKVu8Vvt2zGp3ackRDUEgH8',
    appId: '1:1026142335848:ios:ebac057efec32705bb5cdd',
    messagingSenderId: '1026142335848',
    projectId: 'bookrading',
    storageBucket: 'bookrading.appspot.com',
    iosClientId: '1026142335848-6ua5s5e2g4tnoj9j4dqk0nd5piqg9k68.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA7zuP9sptXKVu8Vvt2zGp3ackRDUEgH8',
    appId: '1:1026142335848:ios:ebac057efec32705bb5cdd',
    messagingSenderId: '1026142335848',
    projectId: 'bookrading',
    storageBucket: 'bookrading.appspot.com',
    iosClientId: '1026142335848-6ua5s5e2g4tnoj9j4dqk0nd5piqg9k68.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookradingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBibKzR061047KehYKc6dKsKjJ0RPKlAd4',
    appId: '1:1026142335848:web:fa393514aba44adcbb5cdd',
    messagingSenderId: '1026142335848',
    projectId: 'bookrading',
    authDomain: 'bookrading.firebaseapp.com',
    storageBucket: 'bookrading.appspot.com',
    measurementId: 'G-7H66DFXCPN',
  );
}
